### ISSUE TITLE
Tunnel error: Error: getaddrinfo ESRCH

### ISSUE THREAD

**Issue by leungjianjun** [igrigorik/node-spdyproxy#58]
Hello，
I deploy the proxy to the VPS, and everything is OK. But when the connections rise, there are tons of "Tunnel error: Error: getaddrinfo ESRCH" in the log.
...
Thu Mar 19 2015 09:28:16 GMT+0000 (UTC) Tunnel error: Error: connect EMFILE
Thu Mar 19 2015 09:28:16 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
Thu Mar 19 2015 09:28:16 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
Thu Mar 19 2015 09:28:16 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
Thu Mar 19 2015 09:28:20 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
Thu Mar 19 2015 09:28:20 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
Thu Mar 19 2015 09:28:21 GMT+0000 (UTC) Tunnel error: Error: getaddrinfo ESRCH
...
I change the VPS max open file limit
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 14873
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 14873
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

But it doesn't work.

**Comment by igrigorik** [comment]
This is not a spdyproxy issue. It looks like you're exhausting your system resources. Take a look at:
- http://stackoverflow.com/questions/10355501/connect-emfile-error-in-node-js

**Comment by leungjianjun** [comment]
Thanks for reply.
I google it and also find this answer. I have changed the VPS setting, and there are only a few "EMFILE" errors. But there are still many "ESRCH" errors. I also google it, but there is no result about this error.
Besides I also get many "Client error: socket hang up" errors.
