### ISSUE TITLE
running "npm install -g spdyproxy" encounter errors,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [igrigorik/node-spdyproxy#59]
root@133-130-58-26:~# npm install -g spdyproxy
npm http GET https://registry.npmjs.org/spdyproxy
npm http GET https://registry.npmjs.org/spdyproxy
npm http GET https://registry.npmjs.org/spdyproxy
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:440:26)
npm ERR!     at ClientRequest.g (events.js:185:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:88:17)
npm ERR!     at HTTPParser.parserOnIncomingClient (http.js:1445:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData (http.js:1356:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:396:27)
npm ERR!     at SecurePair.cycle (tls.js:750:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:131:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "spdyproxy"
npm ERR! node -v v0.8.2
npm ERR! npm -v 1.1.36
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@133-130-58-26:~#

tks a lot

**Comment by igrigorik** [comment]
This looks like an NPM error, not a spdyproxy error. 

See: http://stackoverflow.com/questions/9626990/receiving-error-error-ssl-error-self-signed-cert-in-chain-while-using-npm

**Comment by luckypoem** [comment]
HI.
I USE NODE-V0.8.23,AFTER I DELETE THIS VERSION AND RECOMPILE NODE-V0.12.7,THEN I CAN 
RUN "npm install -g spdyproxy" SUCCESSFULLY.
